name: CI

on:
  push:
    branches:
      - main
      - majTests
  pull_request:
    branches:
      - main
      - majTests

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/p14critipixel

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: p14critipixel
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Create database
        run: php bin/console doctrine:database:create --env=test

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Run CS Fixer
        run: vendor/bin/php-cs-fixer check

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Compile assets
        run: php bin/console asset-map:compile

      - name: Run tests
        run: vendor/bin/phpunit